site_name: Veracode Declare
site_description: 'Veracode Declare'
site_author: 'sebcoles'
docs_dir: docs/
repo_name: 'Veracode.OSS.Delcare'
repo_url: 'https://github.com/sebcoles/Veracode.OSS.Declare/'
theme:
  name: 'material'
  features:
    - navigation.instant
nav:
    - Home: index.md
    - Getting Started: getting_started.md
    - Actions:
        - Configure: actions/configure.md
        - Test: actions/test.md
        - Scan: actions/scan.md
        - Evaluate: actions/evaluate.md
        - Mitigation: actions/mitigation.md
        - Delete: actions/delete.md
    - Download:
        - Artifactory: download/artifactory.md
    - Integrations:
        - GitHub: integrations/github.md
        - TeamCity: integrations/teamcity.md
        - Jenkins: integrations/teamcity.md
        - Docker: integrations/teamcity.md